// export const techMap: { [key: string]: string } = {
//   // JavaScript variations
//   javascript: 'devicon-javascript-plain',
//   js: 'devicon-javascript-plain',

//   // TypeScript variations
//   typescript: 'devicon-typescript-plain',
//   ts: 'devicon-typescript-plain',

//   // React variations
//   react: 'devicon-react-original',
//   reactjs: 'devicon-react-original',

//   // Next.js variations
//   nextjs: 'devicon-nextjs-plain',
//   next: 'devicon-nextjs-plain',
//   'next-js': 'devicon-nextjs-plain',

//   // Node.js variations
//   nodejs: 'devicon-nodejs-plain',
//   node: 'devicon-nodejs-plain',

//   // Bun.js variations
//   bun: 'devicon-bun-plain',
//   bunjs: 'devicon-bun-plain',

//   // Deno.js variations
//   deno: 'devicon-denojs-original',
//   denojs: 'devicon-denojs-plain',

//   // Python variations
//   python: 'devicon-python-plain',

//   // Java variations
//   java: 'devicon-java-plain',

//   // C++ variations
//   'c++': 'devicon-cplusplus-plain',
//   cpp: 'devicon-cplusplus-plain',

//   // C# variations
//   'c#': 'devicon-csharp-plain',
//   csharp: 'devicon-csharp-plain',

//   // PHP variations
//   php: 'devicon-php-plain',

//   // HTML variations
//   html: 'devicon-html5-plain',
//   html5: 'devicon-html5-plain',

//   // CSS variations
//   css: 'devicon-css3-plain',
//   css3: 'devicon-css3-plain',

//   // Git variations
//   git: 'devicon-git-plain',

//   // Docker variations
//   docker: 'devicon-docker-plain',

//   // MongoDB variations
//   mongodb: 'devicon-mongodb-plain',
//   mongo: 'devicon-mongodb-plain',

//   // MySQL variations
//   mysql: 'devicon-mysql-plain',

//   // PostgreSQL variations
//   postgresql: 'devicon-postgresql-plain',
//   postgres: 'devicon-postgresql-plain',

//   // AWS variations
//   aws: 'devicon-amazonwebservices-original',
//   'amazon web services': 'devicon-amazonwebservices-original',

//   // Tailwind CSS variations
//   tailwind: 'devicon-tailwindcss-original',
//   tailwindcss: 'devicon-tailwindcss-original',

//   // Redux
//   redux: 'devicon-redux-original',
// };

export const techMap: { [key: string]: string } = {
  // JavaScript variations
  javascript: 'devicon-javascript-plain',
  js: 'devicon-javascript-plain',

  // TypeScript variations
  typescript: 'devicon-typescript-plain',
  ts: 'devicon-typescript-plain',

  // React variations
  react: 'devicon-react-original',
  reactjs: 'devicon-react-original',

  // Next.js variations
  nextjs: 'devicon-nextjs-plain',
  next: 'devicon-nextjs-plain',
  'next-js': 'devicon-nextjs-plain',

  // Node.js variations
  nodejs: 'devicon-nodejs-plain',
  node: 'devicon-nodejs-plain',

  // Bun.js variations
  bun: 'devicon-bun-plain',
  bunjs: 'devicon-bun-plain',

  // Deno.js variations
  deno: 'devicon-denojs-original',
  denojs: 'devicon-denojs-plain',

  // Python variations
  python: 'devicon-python-plain',

  // Java variations
  java: 'devicon-java-plain',

  // C++ variations
  'c++': 'devicon-cplusplus-plain',
  cpp: 'devicon-cplusplus-plain',

  // C# variations
  'c#': 'devicon-csharp-plain',
  csharp: 'devicon-csharp-plain',

  // PHP variations
  php: 'devicon-php-plain',

  // HTML variations
  html: 'devicon-html5-plain',
  html5: 'devicon-html5-plain',

  // CSS variations
  css: 'devicon-css3-plain',
  css3: 'devicon-css3-plain',

  // Git variations
  git: 'devicon-git-plain',

  // Docker variations
  docker: 'devicon-docker-plain',

  // MongoDB variations
  mongodb: 'devicon-mongodb-plain',
  mongo: 'devicon-mongodb-plain',

  // MySQL variations
  mysql: 'devicon-mysql-plain',

  // PostgreSQL variations
  postgresql: 'devicon-postgresql-plain',
  postgres: 'devicon-postgresql-plain',

  // AWS variations
  aws: 'devicon-amazonwebservices-original',
  'amazon web services': 'devicon-amazonwebservices-original',

  // Tailwind CSS variations
  tailwind: 'devicon-tailwindcss-original',
  tailwindcss: 'devicon-tailwindcss-original',

  // Redux
  redux: 'devicon-redux-original',

  // Custom tech names with fallbacks
  threedsmax: 'devicon-devicon-plain',
  aarch64: 'devicon-devicon-plain',
  adonisjs: 'devicon-devicon-plain',
  aftereffects: 'devicon-devicon-plain',
  akka: 'devicon-devicon-plain',
  algolia: 'devicon-devicon-plain',
  alpinejs: 'devicon-alpinejs-plain',
  amazonwebservices: 'devicon-amazonwebservices-original',
  anaconda: 'devicon-devicon-plain',
  android: 'devicon-android-plain',
  androidstudio: 'devicon-devicon-plain',
  angular: 'devicon-angularjs-plain',
  angularjs: 'devicon-angularjs-plain',
  angularmaterial: 'devicon-devicon-plain',
  ansible: 'devicon-devicon-plain',
  antdesign: 'devicon-devicon-plain',
  apache: 'devicon-apache-original',
  apacheairflow: 'devicon-devicon-plain',
  apachekafka: 'devicon-devicon-plain',
  apachespark: 'devicon-devicon-plain',
  apl: 'devicon-devicon-plain',
  appcelerator: 'devicon-devicon-plain',
  apple: 'devicon-devicon-plain',
  appwrite: 'devicon-devicon-plain',
  archlinux: 'devicon-devicon-plain',
  arduino: 'devicon-devicon-plain',
  argocd: 'devicon-devicon-plain',
  astro: 'devicon-devicon-plain',
  atom: 'devicon-devicon-plain',
  awk: 'devicon-devicon-plain',
  axios: 'devicon-devicon-plain',
  azure: 'devicon-azure-plain',
  azuredevops: 'devicon-devicon-plain',
  azuresqldatabase: 'devicon-devicon-plain',
  babel: 'devicon-devicon-plain',
  backbonejs: 'devicon-devicon-plain',
  ballerina: 'devicon-devicon-plain',
  bamboo: 'devicon-devicon-plain',
  bash: 'devicon-bash-plain',
  beats: 'devicon-devicon-plain',
  behance: 'devicon-devicon-plain',
  bitbucket: 'devicon-devicon-plain',
  blazor: 'devicon-devicon-plain',
  blender: 'devicon-devicon-plain',
  bootstrap: 'devicon-bootstrap-plain',
  bower: 'devicon-devicon-plain',
  browserstack: 'devicon-devicon-plain',
  bulma: 'devicon-devicon-plain',
  bun: 'devicon-bun-plain',
  c: 'devicon-c-plain',
  cairo: 'devicon-devicon-plain',
  cakephp: 'devicon-devicon-plain',
  canva: 'devicon-devicon-plain',
  capacitor: 'devicon-devicon-plain',
  carbon: 'devicon-devicon-plain',
  cassandra: 'devicon-devicon-plain',
  centos: 'devicon-devicon-plain',
  ceylon: 'devicon-devicon-plain',
  chrome: 'devicon-devicon-plain',
  circleci: 'devicon-devicon-plain',
  clarity: 'devicon-devicon-plain',
  clion: 'devicon-devicon-plain',
  clojure: 'devicon-clojure-plain',
  clojurescript: 'devicon-devicon-plain',
  cloudflare: 'devicon-cloudflare-plain',
  cloudflareworkers: 'devicon-devicon-plain',
  cmake: 'devicon-devicon-plain',
  codeac: 'devicon-devicon-plain',
  codecov: 'devicon-devicon-plain',
  codeigniter: 'devicon-codeigniter-plain',
  codepen: 'devicon-devicon-plain',
  coffeescript: 'devicon-devicon-plain',
  composer: 'devicon-devicon-plain',
  confluence: 'devicon-devicon-plain',
  consul: 'devicon-devicon-plain',
  contao: 'devicon-devicon-plain',
  corejs: 'devicon-devicon-plain',
  cosmosdb: 'devicon-devicon-plain',
  couchbase: 'devicon-devicon-plain',
  couchdb: 'devicon-devicon-plain',
  cplusplus: 'devicon-cplusplus-plain',
  crystal: 'devicon-devicon-plain',

  cucumber: 'devicon-devicon-plain',
  cypressio: 'devicon-devicon-plain',
  d3js: 'devicon-devicon-plain',
  dart: 'devicon-dart-plain',
  datagrip: 'devicon-devicon-plain',
  dataspell: 'devicon-devicon-plain',
  dbeaver: 'devicon-devicon-plain',
  debian: 'devicon-devicon-plain',

  devicon: 'devicon-devicon-plain',
  digitalocean: 'devicon-devicon-plain',
  discordjs: 'devicon-devicon-plain',
  django: 'devicon-django-plain',
  djangorest: 'devicon-devicon-plain',

  doctrine: 'devicon-devicon-plain',
  dotnetcore: 'devicon-dotnetcore-plain',
  'dot-net': 'devicon-dotnet-plain',
  dreamweaver: 'devicon-devicon-plain',
  dropwizard: 'devicon-devicon-plain',
  drupal: 'devicon-devicon-plain',
  dynamodb: 'devicon-devicon-plain',
  eclipse: 'devicon-devicon-plain',
  ecto: 'devicon-devicon-plain',
  elasticsearch: 'devicon-devicon-plain',
  electron: 'devicon-electron-original',
  eleventy: 'devicon-devicon-plain',
  elixir: 'devicon-devicon-plain',
  elm: 'devicon-devicon-plain',
  emacs: 'devicon-devicon-plain',
  embeddedc: 'devicon-devicon-plain',
  ember: 'devicon-devicon-plain',
  envoy: 'devicon-devicon-plain',
  erlang: 'devicon-devicon-plain',
  eslint: 'devicon-devicon-plain',
  express: 'devicon-express-original',
  facebook: 'devicon-devicon-plain',
  fastapi: 'devicon-devicon-plain',
  fastify: 'devicon-devicon-plain',
  faunadb: 'devicon-devicon-plain',
  feathersjs: 'devicon-devicon-plain',
  fedora: 'devicon-devicon-plain',
  figma: 'devicon-devicon-plain',
  filezilla: 'devicon-devicon-plain',
  firebase: 'devicon-firebase-plain',
  firefox: 'devicon-devicon-plain',
  flask: 'devicon-flask-original',
  flutter: 'devicon-flutter-plain',
  fortran: 'devicon-devicon-plain',
  foundation: 'devicon-devicon-plain',
  framermotion: 'devicon-devicon-plain',
  framework7: 'devicon-devicon-plain',
  fsharp: 'devicon-devicon-plain',
  gatling: 'devicon-devicon-plain',
  gatsby: 'devicon-gatsby-plain',
  gazebo: 'devicon-devicon-plain',
  gcc: 'devicon-devicon-plain',
  gentoo: 'devicon-devicon-plain',
  ghost: 'devicon-devicon-plain',
  gimp: 'devicon-devicon-plain',
  gitbook: 'devicon-devicon-plain',
  github: 'devicon-github-original',
  githubactions: 'devicon-devicon-plain',
  githubcodespaces: 'devicon-devicon-plain',
  gitlab: 'devicon-devicon-plain',
  gitpod: 'devicon-devicon-plain',
  gitter: 'devicon-devicon-plain',
  go: 'devicon-go-plain',
  godot: 'devicon-devicon-plain',
  goland: 'devicon-devicon-plain',
  google: 'devicon-devicon-plain',
  googlecloud: 'devicon-devicon-plain',
  gradle: 'devicon-devicon-plain',
  grafana: 'devicon-devicon-plain',
  grails: 'devicon-devicon-plain',
  graphql: 'devicon-graphql-plain',
  groovy: 'devicon-devicon-plain',
  grpc: 'devicon-devicon-plain',
  grunt: 'devicon-devicon-plain',
  gulp: 'devicon-devicon-plain',
  hadoop: 'devicon-devicon-plain',
  handlebars: 'devicon-devicon-plain',
  hardhat: 'devicon-devicon-plain',
  harvester: 'devicon-devicon-plain',
  haskell: 'devicon-devicon-plain',
  haxe: 'devicon-devicon-plain',
  helm: 'devicon-devicon-plain',
  heroku: 'devicon-heroku-plain',
  hibernate: 'devicon-devicon-plain',
  homebrew: 'devicon-devicon-plain',
  hugo: 'devicon-devicon-plain',
  ie10: 'devicon-devicon-plain',
  ifttt: 'devicon-devicon-plain',
  illustrator: 'devicon-devicon-plain',
  influxdb: 'devicon-devicon-plain',
  inkscape: 'devicon-devicon-plain',
  insomnia: 'devicon-devicon-plain',
  intellij: 'devicon-intellij-plain',
  ionic: 'devicon-devicon-plain',
  jaegertracing: 'devicon-devicon-plain',
  jamstack: 'devicon-devicon-plain',
  jasmine: 'devicon-devicon-plain',
  junit: 'devicon-devicon-plain',
  jupyter: 'devicon-devicon-plain',
  k3os: 'devicon-devicon-plain',
  k3s: 'devicon-devicon-plain',
  k6: 'devicon-devicon-plain',
  kaggle: 'devicon-devicon-plain',
  karatelabs: 'devicon-devicon-plain',
  karma: 'devicon-devicon-plain',
  kdeneon: 'devicon-devicon-plain',
  keras: 'devicon-devicon-plain',
  kibana: 'devicon-devicon-plain',
  knexjs: 'devicon-devicon-plain',
  knockout: 'devicon-devicon-plain',
  kotlin: 'devicon-kotlin-plain',
  krakenjs: 'devicon-devicon-plain',
  ktor: 'devicon-devicon-plain',
  kubernetes: 'devicon-kubernetes-plain',
  labview: 'devicon-devicon-plain',
  laravel: 'devicon-laravel-plain',
  latex: 'devicon-devicon-plain',
  less: 'devicon-devicon-plain',
  linkedin: 'devicon-devicon-plain',
  linux: 'devicon-linux-plain',
  liquibase: 'devicon-devicon-plain',
  livewire: 'devicon-devicon-plain',
  llvm: 'devicon-devicon-plain',
  lodash: 'devicon-devicon-plain',
  logstash: 'devicon-devicon-plain',
  lua: 'devicon-devicon-plain',
  lumen: 'devicon-devicon-plain',
  magento: 'devicon-devicon-plain',
  mariadb: 'devicon-devicon-plain',
  markdown: 'devicon-devicon-plain',
  materializecss: 'devicon-devicon-plain',
  materialui: 'devicon-materialui-plain',
  matlab: 'devicon-devicon-plain',
  matplotlib: 'devicon-devicon-plain',
  maven: 'devicon-devicon-plain',
  maya: 'devicon-devicon-plain',
  meteor: 'devicon-devicon-plain',
  microsoftsqlserver: 'devicon-devicon-plain',
  minitab: 'devicon-devicon-plain',
  mithril: 'devicon-devicon-plain',
  mobx: 'devicon-devicon-plain',
  mocha: 'devicon-devicon-plain',
  modx: 'devicon-devicon-plain',
  moleculer: 'devicon-devicon-plain',

  mongoose: 'devicon-devicon-plain',
  moodle: 'devicon-devicon-plain',
  msdos: 'devicon-devicon-plain',

  nano: 'devicon-devicon-plain',
  neo4j: 'devicon-devicon-plain',
  neovim: 'devicon-devicon-plain',
  nestjs: 'devicon-devicon-plain',
  netlify: 'devicon-devicon-plain',
  networkx: 'devicon-devicon-plain',
  nginx: 'devicon-nginx-original',
  ngrx: 'devicon-devicon-plain',
  nhibernate: 'devicon-devicon-plain',
  nim: 'devicon-devicon-plain',
  nimble: 'devicon-devicon-plain',
  nixos: 'devicon-devicon-plain',
  nodewebkit: 'devicon-devicon-plain',
  nomad: 'devicon-devicon-plain',
  norg: 'devicon-devicon-plain',
  notion: 'devicon-devicon-plain',
  npm: 'devicon-npm-original-wordmark',
  nuget: 'devicon-devicon-plain',
  numpy: 'devicon-devicon-plain',
  nuxtjs: 'devicon-devicon-plain',
  oauth: 'devicon-devicon-plain',
  objectivec: 'devicon-devicon-plain',
  ocaml: 'devicon-devicon-plain',
  ohmyzsh: 'devicon-devicon-plain',
  okta: 'devicon-devicon-plain',
  openal: 'devicon-devicon-plain',
  openapi: 'devicon-devicon-plain',
  opencl: 'devicon-devicon-plain',
  opencv: 'devicon-devicon-plain',
  opengl: 'devicon-devicon-plain',
  openstack: 'devicon-devicon-plain',
  opensuse: 'devicon-devicon-plain',
  opentelemetry: 'devicon-devicon-plain',
  opera: 'devicon-devicon-plain',
  oracle: 'devicon-devicon-plain',
  ory: 'devicon-devicon-plain',
  p5js: 'devicon-devicon-plain',
  packer: 'devicon-devicon-plain',
  pandas: 'devicon-devicon-plain',
  perl: 'devicon-devicon-plain',
  pfsense: 'devicon-devicon-plain',
  phalcon: 'devicon-devicon-plain',
  phoenix: 'devicon-devicon-plain',
  photonengine: 'devicon-devicon-plain',
  photoshop: 'devicon-devicon-plain',
  phpstorm: 'devicon-phpstorm-plain',
  playwright: 'devicon-devicon-plain',
  plotly: 'devicon-devicon-plain',
  pnpm: 'devicon-devicon-plain',
  podman: 'devicon-devicon-plain',
  poetry: 'devicon-devicon-plain',
  polygon: 'devicon-devicon-plain',
  portainer: 'devicon-devicon-plain',
  postcss: 'devicon-devicon-plain',
  postman: 'devicon-postman-original',
  powershell: 'devicon-powershell-plain',
  premierepro: 'devicon-devicon-plain',
  prisma: 'devicon-devicon-plain',
  processing: 'devicon-devicon-plain',
  prolog: 'devicon-devicon-plain',
  prometheus: 'devicon-devicon-plain',
  protractor: 'devicon-devicon-plain',
  pulsar: 'devicon-devicon-plain',
  pulumi: 'devicon-devicon-plain',
  puppeteer: 'devicon-devicon-plain',
  purescript: 'devicon-devicon-plain',
  putty: 'devicon-devicon-plain',
  pycharm: 'devicon-pycharm-plain',
  pypi: 'devicon-devicon-plain',
  pyscript: 'devicon-devicon-plain',
  pytest: 'devicon-devicon-plain',
  pytorch: 'devicon-devicon-plain',
  qodana: 'devicon-devicon-plain',
  qt: 'devicon-devicon-plain',
  quarkus: 'devicon-devicon-plain',
  quasar: 'devicon-devicon-plain',
  qwik: 'devicon-devicon-plain',
  r: 'devicon-r-plain',
  rabbitmq: 'devicon-devicon-plain',
  rails: 'devicon-rails-plain',
  railway: 'devicon-devicon-plain',
  rancher: 'devicon-devicon-plain',
  raspberrypi: 'devicon-devicon-plain',
  reach: 'devicon-devicon-plain',
  reactbootstrap: 'devicon-devicon-plain',
  reactnavigation: 'devicon-devicon-plain',
  readthedocs: 'devicon-devicon-plain',
  realm: 'devicon-devicon-plain',
  rect: 'devicon-devicon-plain',
  redhat: 'devicon-devicon-plain',
  redis: 'devicon-redis-plain',

  renpy: 'devicon-devicon-plain',
  replit: 'devicon-devicon-plain',
  rider: 'devicon-devicon-plain',
  rocksdb: 'devicon-devicon-plain',
  rockylinux: 'devicon-devicon-plain',
  rollup: 'devicon-devicon-plain',
  ros: 'devicon-devicon-plain',
  rspec: 'devicon-devicon-plain',
  rstudio: 'devicon-rstudio-plain',
  ruby: 'devicon-ruby-plain',
  rubymine: 'devicon-devicon-plain',
  rust: 'devicon-rust-plain',
  rxjs: 'devicon-devicon-plain',
  safari: 'devicon-devicon-plain',
  salesforce: 'devicon-devicon-plain',
  sanity: 'devicon-devicon-plain',
  sass: 'devicon-sass-original',
  scala: 'devicon-devicon-plain',
  scalingo: 'devicon-devicon-plain',
  scikitlearn: 'devicon-devicon-plain',
  sdl: 'devicon-devicon-plain',
  selenium: 'devicon-devicon-plain',
  sema: 'devicon-devicon-plain',
  sentry: 'devicon-devicon-plain',
  reactrouter: 'devicon-devicon-plain',
  sequelize: 'devicon-devicon-plain',
  shopware: 'devicon-devicon-plain',
  shotgrid: 'devicon-devicon-plain',
  sketch: 'devicon-devicon-plain',
  slack: 'devicon-devicon-plain',
  socketio: 'devicon-devicon-plain',
  solidity: 'devicon-devicon-plain',
  solidjs: 'devicon-devicon-plain',
  sonarqube: 'devicon-devicon-plain',
  sourcetree: 'devicon-devicon-plain',
  spack: 'devicon-devicon-plain',
  splunk: 'devicon-devicon-plain',
  spring: 'devicon-devicon-plain',
  spss: 'devicon-devicon-plain',
  spyder: 'devicon-devicon-plain',
  sqlalchemy: 'devicon-devicon-plain',
  sqldeveloper: 'devicon-devicon-plain',
  sqlite: 'devicon-devicon-plain',
  ssh: 'devicon-devicon-plain',
  stackoverflow: 'devicon-devicon-plain',
  stata: 'devicon-devicon-plain',
  storybook: 'devicon-devicon-plain',
  streamlit: 'devicon-devicon-plain',
  stylus: 'devicon-devicon-plain',
  subversion: 'devicon-devicon-plain',
  supabase: 'devicon-devicon-plain',
  svelte: 'devicon-svelte-plain',
  swagger: 'devicon-devicon-plain',
  swift: 'devicon-swift-plain',
  swiper: 'devicon-devicon-plain',
  symfony: 'devicon-devicon-plain',
  tex: 'devicon-devicon-plain',
  tensorflow: 'devicon-devicon-plain',
  terraform: 'devicon-devicon-plain',
  threejs: 'devicon-threejs-plain',
  tomcat: 'devicon-tomcat-plain',
  tortoisegit: 'devicon-devicon-plain',
  towergit: 'devicon-devicon-plain',
  traefikmesh: 'devicon-devicon-plain',
  travis: 'devicon-devicon-plain',
  trello: 'devicon-devicon-plain',
  trpc: 'devicon-devicon-plain',
  twitter: 'devicon-devicon-plain',
  vuejs: 'devicon-vuejs-plain',
  vuestorefront: 'devicon-devicon-plain',
  vuetify: 'devicon-vuetify-plain',
  vyper: 'devicon-devicon-plain',
  wasm: 'devicon-devicon-plain',
  webflow: 'devicon-devicon-plain',
  weblate: 'devicon-devicon-plain',
  webpack: 'devicon-webpack-plain',
  webstorm: 'devicon-webstorm-plain',
  windows11: 'devicon-devicon-plain',
  windows8: 'devicon-devicon-plain',
  woocommerce: 'devicon-devicon-plain',
  wordpress: 'devicon-devicon-plain',
  xamarin: 'devicon-xamarin-original',
  xcode: 'devicon-xcode-plain',
  xd: 'devicon-devicon-plain',
  xml: 'devicon-devicon-plain',
  yaml: 'devicon-devicon-plain',
  yarn: 'devicon-devicon-plain',
  yii: 'devicon-devicon-plain',
  yugabytedb: 'devicon-devicon-plain',
  yunohost: 'devicon-devicon-plain',
  zend: 'devicon-devicon-plain',
  zig: 'devicon-devicon-plain',
};
